### ISSUE TITLE
Portfolio: application deploy

### ISSUE THREAD

**Issue by jaredatandi** [jaredatandi/Portfolio#13]
## EarlierDeployment
I had made an earlier deployment so I am making an issue with the link to the portfolio.
[Deployed here](https://jaredatandi.github.io/Portfolio/)

**Comment by Olamarx** [comment]
> ## EarlierDeployment
> I had made an earlier deployment so I am making an issue with the link to the portfolio. [Deployed here](https://jaredatandi.github.io/Portfolio/)

Hi @jaredatandi, 

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media3.giphy.com/media/VlqzeaRnhCvPLfrSh6/giphy.gif"/>

## Highlights
- Good use of GitHub pages ✔️ 

## Required Changes ♻️
_Check the comments under the review._

- [ ] Kindly update your readme file to have the live demo included.


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by jaredatandi** [comment]
Hi @Olamarx I have added the llink

**Comment by emmiiorji** [comment]
Hi @jaredatandi, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Red-approved](https://user-images.githubusercontent.com/20554583/199362837-208e4c72-b63b-4cdb-a8ed-cebfdac94960.gif)

## Good Highlights

- Repo is professional
- Project is live

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
